npm install express --save
npm install ejs --save
npm install cookie-parser --save
npm install express-session --save
npm install request --save
npm install request-promise --save
npm install morgan --save
npm install mysql --save
npm install body-parser --save
npm install passport --save
npm install connect-flash --save
npm install passport-google-oauth --save
npm install passport-local --save
npm install passport-facebook --save
npm install bcrypt --save
npm install uuid --save
